# Generated by Django 3.2 on 2022-01-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observacion',
            field=models.TextField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=49),
        ),
    ]
