# Generated by Django 3.2 on 2022-01-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20220121_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
