# Generated by Django 3.2 on 2022-01-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_precio_precio_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
